name: mlflow-ci  # Nama environment
channels:
  - defaults
dependencies:
  - python=3.10  # Sesuaikan dengan versi Python yang Anda inginkan
  - pip  # Install pip di environment conda
  - pip:
      - mlflow  # Install MLflow menggunakan pip
      - pandas  # Install pandas untuk data manipulation
      - numpy   # Install numpy untuk operasi numerik
      - scikit-learn  # Install scikit-learn untuk machine learning
      - matplotlib  # Install matplotlib untuk plotting
      - seaborn  # Install seaborn untuk visualisasi data
