name: mlflow-ci
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - pip
  - pip:
      - mlflow  # Install mlflow via pip instead of conda
      - git+https://github.com/mlflow/mlflow.git
