name: mlflow-project  # Nama environment

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8  # Versi Python yang lebih stabil, sesuaikan dengan yang kamu butuhkan (misalnya 3.8 atau 3.9)
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
  # Tambahkan dependensi lainnya jika diperlukan
