name: mlflow-project
channels:
  - conda-forge   # Menambahkan channel conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - pandas
  - mlflow=2.7.0  # Gunakan versi stabil mlflow
  - pip
  - pip:
      - gunicorn
