name: mlflow-ci
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - mlflow=2.5.1  # Tentukan versi MLflow yang lebih spesifik
  - pip
  - pip:
      - git+https://github.com/mlflow/mlflow.git
