name: mlflow-project  # Nama environment

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8  # Sesuaikan dengan versi Python yang kamu butuhkan
  - pip
  - pip:
      - mlflow  # MLflow dan dependensi lain yang dibutuhkan
      - scikit-learn  # Contoh tambahan, sesuaikan dengan kebutuhanmu
      - pandas
  